### PR TITLE
Use standard library instead of MFC

### PR DESCRIPTION
**Pull request by s-martin**
See #8 

* converted CString to std::string

### CODE REVIEW

**Comment by s-martin** [comment]
#11 needs to be mergend before this PR

**Comment by vpaladino778** [comment]
Is this PR finished? Or are you still working on it?

**Comment by s-martin** [comment]
sorry, still work in progress

**Comment by vpaladino778** [comment]
No worries at all! Let me know when it's good to go!

**Comment by s-martin** [comment]
#14 should be merged first

**Pull request merged**
